name: Test custom action

on:
  push:
    branches:
      - main

jobs:
  exemplo-de-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v2

      - name: Custom action
        uses: zzfernando/custom-actions-poc@0.1.1
        with:
          who-to-greet: "World"
